icon: 👋
title: "Полноценный пример Vordoc"
description: "Демонстрация кастомных компонентов, ссылок, якорей и авторизации"
header:
  title: "Vordoc Demo"

pages:
  "index.md":
    title: "Полноценный пример Vordoc"
    icon: 👋
    description: "Демонстрация нескольких документаций, кастомных компонентов, ссылок, якорей и авторизации"
    order: 0
